services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: stock_report
      POSTGRES_USER: report
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
